# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:

      # Specify the Xcode version to use
      macos:
        xcode: "9.0"

      steps:
        - checkout

        # Build the app and run tests
        - run:
            name: Build and run tests
            command: fastlane scan
            environment:
              SCAN_DEVICE: iPhone 6
              SCAN_SCHEME: WebTests

        # run tests!
        - run:
            name: run tests
            command: |
              platform=android bundle exec rake wordpress:test