# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: pull apps
          command: |
            wget -o WordPress.apk http://drive.google.com/file/d/1Hb2z7guNc8ch1o11mmuP5aioJ_Endal3/view?usp=sharing

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --retry=3 --path vendor

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}


      # run tests!
      - run:
          name: run tests
          command: |
            platform=android bundle exec rake wordpress:test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/app/WordPress.apk
          destination: test-apps
  # app:
  #   docker:
  #     # specify the version you desire here
  #      - image: python:3.6.0-jessie
  #   working_directory: ~/tmp
  #   steps:
  #     - run:
  #         name: pull app
  #         command: |
  #           curl https://drive.google.com/file/d/1Hb2z7guNc8ch1o11mmuP5aioJ_Endal3/view?usp=sharing --output /tmp/app/WordPress.apk
  #           curl https://drive.google.com/file/d/18ODObtGuG3UYhgst-6h6ucn79_kYTxwD/view?usp=sharing --output /tmp/app/WordPress.app
  #      - store_artifacts:
  #         path: /tmp/app/WordPress.apk
# workflows:
#   version: 2
#   build_and_pull:
#     jobs:
#       - build
#       - app
        
  
  


