# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
      # Specify the Xcode version to use
      macos:
        xcode: "9.3.0"

      shell: /bin/bash --login -eo pipefail

      steps:
        - checkout

        - run: |
            curl -L -o ./sdk.zip https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip

        - run: unzip ./sdk.zip

        - run: echo 'export PATH=$(pwd)/tools:$PATH' >> $BASH_ENV

        - run: echo $PATH

        - run: android

        - run:
            name: Set Ruby Version
            command:  echo "ruby-2.4.1" > ~/.ruby-version

        - run:
            name: Install Project Dependencies
            command: |
              bundle check --path=vendor/bundle || bundle install --retry=3 --path vendor

        - run:
            name: Install appium
            command: |
              npm install -g appium

        - run:
            name: Install allure
            command: |
              brew install allure

        - run:
            name: Download app file
            command: |
              curl -L -o ./apps/WordPress.app.zip "https://drive.google.com/uc?export=download&id=18ODObtGuG3UYhgst-6h6ucn79_kYTxwD"

        - run:
            name: Check available simulators
            command: instruments -s devices

        - run: mkdir ./output

        # run tests!
        - run:
            name: run tests
            command: |
              platform=ios bundle exec rake wordpress:test

        - store_test_results:
            path: ./output

        - store_artifacts:
            path: wordpress-report
            destination: wordpress