# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  android:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout

      - run: |
          echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-28;google_apis;x86_64'
  ios:

      # Specify the Xcode version to use
      macos:
        xcode: "9.3.0"

      shell: /bin/bash --login -eo pipefail

      steps:
        - checkout

        - run:
            name: Set Ruby Version
            command:  echo "ruby-2.4.1" > ~/.ruby-version

        - run:
            name: Install Project Dependencies
            command: |
              bundle check --path=vendor/bundle || bundle install --retry=3 --path vendor

        - run:
            name: Install appium
            command: |
              npm install -g appium

        - run:
            name: Install allure
            command: |
              brew install allure

        - run:
            name: Download app file
            command: |
              curl -L -o ./apps/WordPress.app.zip "https://drive.google.com/uc?export=download&id=18ODObtGuG3UYhgst-6h6ucn79_kYTxwD"

        - run:
            name: Check available simulators
            command: instruments -s devices

        - run: mkdir ./output

        # run tests!
        - run:
            name: run tests
            command: |
              platform=ios bundle exec rake wordpress:test

        - store_test_results:
            path: ./output

        - store_artifacts:
            path: wordpress-report
            destination: wordpress
workflows:
  version: 2
  build_and_test:
    jobs:
      - android
      - ios

